import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";
import NavComponent from "../(home)/Navbar/NavComponent";
import FooterPageComponent from "../(home)/Footer/FooterPageComponent";

const DMSans = localFont({
  src: [
    {
      path: "../../../public/fonts/dm-sans/DMSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../public/fonts/dm-sans/DMSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Finniu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <NavComponent />
        {children}
        <FooterPageComponent />
      </body>
    </html>
  );
}
