import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavComponent from "./components/NavComponent";
import FooterPageComponent from "./components/FooterPageComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finniu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavComponent />
        {children}

        <FooterPageComponent />
      </body>
    </html>
  );
}
