import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavComponent from "./components/Navbar/NavComponent";
import FooterPageComponent from "./components/Footer/FooterPageComponent";

const DMSans = localFont({
  src: "../public/fonts/Dm-sans/DMSans-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Finniu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <NavComponent />
        {children}
        <FooterPageComponent />
      </body>
    </html>
  );
}
