import type { Metadata } from "next";
import localFont from 'next/font/local';
// import { Inter } from "next/font/google";
import "./globals.css";
import NavComponent from "./components/Navbar/NavComponent";
import FooterPageComponent from "./components/Footer/FooterPageComponent";
import local from "next/font/local";

// const inter = Inter({ subsets: ["latin"] });

const comfortaa = localFont({src: '../public/fonts/Comfortaa/Comfortaa-Regular.ttf'});

export const metadata: Metadata = {
  title: "Finniu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <NavComponent />
        {children}
        <FooterPageComponent />
      </body>
    </html>
  );
}
